services:
  web:
    build:
      context: .
      dockerfile: ./Aberturas/Dockerfile
    env_file:
      - .env
    volumes:
      - ./Aberturas/storage:/app/storage
      - ./Aberturas/tmp:/app/tmp
    ports:
      - "${RAILS_PORT:-3000}:3000"
    environment:
      - RAILS_ENV=${RAILS_ENV:-development}
    depends_on:
      - db
    stdin_open: true
    tty: true
    restart: unless-stopped
    container_name: web

  # Servicio de Postgres solo para desarrollo
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Acma2024!Secure}
      POSTGRES_DB: ${DEV_POSTGRES_DB:-acma_development}
    ports:
      - "5433:5432"  # Exponemos 5433 solo para desarrollo
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - default

volumes:
  pgdata:

networks:
  default:
