services:
  web:
    build:
      context: .
      dockerfile: ./Aberturas/Dockerfile
    env_file:
      - .env
    volumes:
      - ./Aberturas:/app
    ports:
      - "${RAILS_PORT:-3000}:3000"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    stdin_open: true
    tty: true
    restart: unless-stopped
    container_name: web
    profiles: ["development", "production"]
    networks:
      - acma_net

  db:
    image: postgres:17
    profiles: ["development"]
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DEV_POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - acma_net

volumes:
  pgdata:

networks:
  acma_net:
    driver: bridge
