default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] %>

production:
  primary:
    <<: *default
  cache:
    <<: *default
    database: <%= ENV['PROD_POSTGRES_DB'] %>_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: <%= ENV['PROD_POSTGRES_DB'] %>_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: <%= ENV['PROD_POSTGRES_DB'] %>_cable
    migrations_paths: db/cable_migrate

development:
  primary:
    <<: *default
    database: <%= ENV['DEV_POSTGRES_DB'] %>

test:
  primary:
    <<: *default
    database: aberturas_test
    host: localhost
    username: postgres
    password: postgres
