default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: <%= ENV.fetch("DATABASE_HOST") { "host.docker.internal" } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "Acma2024!Secure" } %>

production:
  primary:
    <<: *default
    database: <%= ENV.fetch("PROD_POSTGRES_DB") { "acma_production" } %>
  cache:
    <<: *default
    database: <%= ENV.fetch("PROD_POSTGRES_DB") { "acma_production" } %>_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: <%= ENV.fetch("PROD_POSTGRES_DB") { "acma_production" } %>_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: <%= ENV.fetch("PROD_POSTGRES_DB") { "acma_production" } %>_cable
    migrations_paths: db/cable_migrate

development:
  primary:
    <<: *default
    database: <%= ENV.fetch("DEV_POSTGRES_DB") { "acma_development" } %>
