production:
  update_official_rate_weekdays:
    class: UpdateOfficialRateJob
    queue: default
    args: ['automatic']
    schedule: at 9:00am on weekdays
  update_official_rate_saturday:
    class: UpdateOfficialRateJob
    queue: default
    args: ['automatic']
    schedule: at 10:00am on saturday

development:
  update_official_rate_weekdays:
    class: UpdateOfficialRateJob
    queue: default
    args: ['automatic']
    schedule: at 9:00am on weekdays
  update_official_rate_saturday:
    class: UpdateOfficialRateJob
    queue: default
    args: ['automatic']
    schedule: at 10:00am on saturday

test:
  # No scheduled jobs in test environment
